version: '3.3'
services:
    prometheus:
        ports:
            - '9090:9090'
        volumes:
            - ./data/prometheus:/etc/prometheus
        image: prom/prometheus
    
    simple-app:
        build:
            context: ./simple-app
            dockerfile: ./simple-app.dockerfile
        restart: always
        ports:
        - "2112:2112"
        deploy:
            mode: replicated
            replicas: 1