version: '3.3'
services:
    prometheus:
        ports:
            - '9090:9090'
        volumes:
            - ./data/prometheus:/etc/prometheus
        image: prom/prometheus
        restart: always

    alertmanager:
        ports:
            - '9093:9093'
        volumes:
            - ./data/alertmanager/:/etc/alertmanager/
        image: prom/alertmanager:v0.12.0
        deploy:
            mode: global
    
    simple-app-01:
        build:
            context: ./simple-app
            dockerfile: ./simple-app.dockerfile
        restart: always
        ports:
        - "2111:2112"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            - APP_NAME=app_01
    
    simple-app-02:
        build:
            context: ./simple-app
            dockerfile: ./simple-app.dockerfile
        restart: always
        ports:
        - "2112:2112"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            - APP_NAME=app_02
    
    simple-app-03:
        build:
            context: ./simple-app
            dockerfile: ./simple-app.dockerfile
        restart: always
        ports:
        - "2113:2112"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            - APP_NAME=app_03